name: g4_viruses
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - blast=2.17.0
  - bwa=0.7.19
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - cffi=2.0.0
  - curl=8.16.0
  - cutadapt=5.2
  - diamond=2.1.14
  - dnaio=1.2.2
  - entrez-direct=24.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=12.1.0
  - htslib=1.22.1
  - icu=75.1
  - isa-l=2.31.1
  - keyutils=1.6.3
  - kraken2=2.1.6
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libcups=2.3.3
  - libcurl=8.16.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mpi=1.0
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - openjdk=24.0.2
  - openmpi=4.1.6
  - openssl=3.5.4
  - pbzip2=1.1.13
  - pcre2=10.46
  - perl=5.32.1
  - perl-archive-tar=3.04
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.214
  - perl-compress-raw-zlib=2.214
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.213
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.04
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.70
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pigz=2.8
  - pip=25.2
  - pixman=0.46.4
  - popt=1.16
  - pthread-stubs=0.4
  - pycparser=2.22
  - python=3.10.19
  - python-isal=1.8.0
  - python-zlib-ng=1.0.0
  - python_abi=3.10
  - readline=8.2
  - rsync=3.4.1
  - samtools=1.22.1
  - seqtk=1.5
  - setuptools=80.9.0
  - spades=4.2.0
  - tar=1.35
  - tk=8.6.13
  - trim-galore=0.6.10
  - tzdata=2025b
  - wget=1.21.4
  - wheel=0.45.1
  - xopen=2.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xxhash=0.8.3
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
